name: remote_rift_mobile
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  draft: ^0.0.12
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  http: ^1.5.0
  json_annotation: ^4.9.0
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3
  slang: ^4.8.1
  slang_flutter: ^4.8.0
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.10.0
  build_runner: ^2.7.0
  draft_builder: ^0.0.4
  # Fixes incompatibility of source_gen 3.1.0 and analyzer 8.4.0.
  analyzer: 8.3.0
  fake_async: ^1.3.3

flutter:
  uses-material-design: true
