name: remote_rift_mobile
description: "A mobile application that allows remote interaction with the League client."
version: 0.9.0+1
publish_to: "none"

environment:
  sdk: ^3.10.0

dependencies:
  cancelable_stream: ^1.0.0
  draft: ^0.0.12
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  http: ^1.5.0
  json_annotation: ^4.9.0
  slang: ^4.8.1
  slang_flutter: ^4.8.0
  vibration: ^3.1.5
  web_socket_channel: ^3.0.3
  equatable: ^2.0.8

  remote_rift_core:
    git:
      url: https://github.com/tomwyr/remote-rift-connector.git
      ref: 0.12.1
      path: packages/core

  remote_rift_ui:
    git:
      url: https://github.com/tomwyr/remote-rift-foundation.git
      ref: 0.9.0
      path: packages/ui

  remote_rift_utils:
    git:
      url: https://github.com/tomwyr/remote-rift-foundation.git
      ref: 0.9.0
      path: packages/utils

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.10.0
  build_runner: ^2.7.0
  draft_builder: ^0.0.13

flutter:
  uses-material-design: true
  assets:
    - assets/
